### ISSUE TITLE
segmentation fault UEDGE with python3 on MacOS

### ISSUE THREAD

**Issue by jguterl** [LLNL/UEDGE#10]
On MacOS Catalina 10.15.2 with Python 3.7.6 and Forthon 0.8.41

Set of instructions leading to the segmentation fault (reproducible):
- git clone https://github.com/LLNL/UEDGE.git
- cd UEDGE
- python setup.py clean
- python setup.py build
- python setup.py install
- cd pyexamples/box2
- add the following function in runcase.py (since execfile is deprecated in python 3) 
```
def execfile(filepath, globals=None, locals=None):
    if globals is None:
        globals = {}
    globals.update({
        "__file__": filepath,
        "__name__": "__main__",
    })
    with open(filepath, 'rb') as file:
        exec(compile(file.read(), filepath, 'exec'), globals, locals)
```
-python runcase.py

output:

[Screen Shot 2020-01-22 at 9 08 25 AM](https://user-images.githubusercontent.com/17376868/72916361-c3092800-3cf6-11ea-9d5a-8b263995b82c.png)

Result of backtrace with lldb:

![Screen Shot 2020-01-22 at 9 09 18 AM](https://user-images.githubusercontent.com/17376868/72916439-e03df680-3cf6-11ea-8cfd-b0cd6ca5f241.png)

**Comment by jguterl** [comment]
The same procedure on Linux(debian version) do not raise segmentation fault.

**Comment by holm10** [comment]
Closing as stale, since the issue is 3.5y old. Possibly related to #42
