### ISSUE TITLE
Possible Glitch oderhs.m

### ISSUE THREAD

**Issue by jguterl** [LLNL/UEDGE#12]
Line 7934 in oderhs.m:
if(isngonxy(ix,iy,ifld) == 1) then 
should read
if(isngonxy(ix,iy,igsp) == 1) then 
?

**Comment by trognlien** [comment]
Thanks Jerome.  Indeed, the subsript should be igsp here, not ifld. Will correct in next version.
  -Tom

**Comment by holm10** [comment]
Closed as solved
