### ISSUE TITLE
Moving to python 3

### ISSUE THREAD

**Issue by sballin** [LLNL/UEDGE#17]
Here are some reasons I think we would benefit from dropping support for python 2:

* Python 2 relies on dead code: the important libraries on this [list](https://python3statement.org/) (including numpy and matplotlib) have pledged to stop updating their python 2 versions before 2020
* Uniform codebase: right now we have a mix of routines, some designed for python 2, others for python 3. Sometimes when you want to use a new script, you need to port it yourself.
* Simplified codebase: remove code that does different things depending on the python version. A smaller and simpler codebase is a more maintainable codebase.
* Old python 2 code would not be gone forever: it's still in the git history if anyone needs to use it

Drawbacks:

* In my experience, Totalview can only show the Fortran source when uedge is used with python 2

I think this task would be pretty simple using the [2to3](https://docs.python.org/2/library/2to3.html) utility, and I would be happy to make a pull request. 

Let me know your thoughts on this, and if there are any drawbacks I'm unaware of.

**Comment by trognlien** [comment]
Hi Sean,
   I think it is fine if you want to proceed with conversions to Python 3 for python routines used to enable pyUedge.  Bill mentioned that have scripts that worked in either Python 2 or 3 would be useful, though this might not be possible.  For the Totalview debugging of the Fortran core of UEDGE, we still have the Basis capability for some of us and that is still very useful.

  -Tom

------
Thomas D. Rognlien                                     Email: trognlien@llnl.gov<mailto:trognlien@llnl.gov>
L-440 (B3725, R432)                                   Tel:  925-422-9830
LLNL, 7000 East Ave, P.O. Box 808           Admin support: 925-422-7446
Livermore, CA 94551

**Comment by holm10** [comment]
Closed as resolved: UEDGE no longer supports Python 2
