### ISSUE TITLE
Jupyter notebook iphibcc = 0

### ISSUE THREAD

**Issue by rmchurch** [LLNL/UEDGE#19]
Newbie trying out the jupyter example notebook using Google Colab (pip install forthon mppl uedge directly in the notebook). I ran into an issue right away, under "Run a Case" I get the following error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-27-3253ef9ba79b> in <module>()
      1 from uedge import *
----> 2 bbb.exmain()   #
      3 print("Usual iteration output should be in terminal window running Jupyter Notebook")
      4 print("nksol ---  iterm = ",bbb.iterm)

RuntimeError: **INPUT ERROR: only iphibcc=1,2,3 available
```
From the boundary.m code, it seems to be true: iphibcc==0 is not allowed. I change by hand:
```
bbb.iphibcc = 1
```
And it works fine. Just wondering if I have something wrong with version installation? Or is this simply an outdated input file?

**Comment by llnl-fesp** [comment]
Most likely an out of date input file. You could edit the first input cell of the notebook and right after "from case_setup import *" add "bbb.iphibcc = 1".  I generally run jupyter notebook locally, I haven't tried google colab for quite a while. I'll give it a try.

Bill
________________________________
From: Michael Churchill ***@***.***>
Sent: Wednesday, June 23, 2021 1:37 PM
To: LLNL/UEDGE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LLNL/UEDGE] Jupyter notebook iphibcc = 0 (#19)


Newbie trying out the jupyter example notebook using Google Colab (pip install forthon mppl uedge directly in the notebook). I ran into an issue right away, under "Run a Case" I get the following error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-27-3253ef9ba79b> in <module>()
      1 from uedge import *
----> 2 bbb.exmain()   #
      3 print("Usual iteration output should be in terminal window running Jupyter Notebook")
      4 print("nksol ---  iterm = ",bbb.iterm)

RuntimeError: **INPUT ERROR: only iphibcc=1,2,3 available


From the boundary.m code, it seems to be true: iphibcc is not allowed. I change by hand:

bbb.iphibcc = 1


And it works fine. Just wondering if I have something wrong with version installation? Or is this simply an outdated input file?

**Comment by rmchurch** [comment]
Right, adding the `bbb.iphibcc = 1` works. Here is the notebook in Colab that runs for me: https://colab.research.google.com/drive/1XqSg-PMeSsDtJHk26Y0gy-X4peazLzo6?usp=sharing
what does `iphibcc` represent? Was it modified to no longer accept 0 as input? I saw something in release notes about it, but didn't understand it. If there is a different example case_setup file that is a good test case, let me know.

**Comment by llnl-fesp** [comment]
I might suggest the following:

import uedge.uedge_lists as ul
ul.list_variable("iphibcc")

This will show:

Package:    bbb
Group:      Bcond
Attributes: Bcond restart
Type:       integer
Address:    4692085296
Unit:
Comment:
core BC at iy=1 when isnewpot=1;iy=0
=1, d^2(ey)/dy^2=0
=2, te=constant & ey(ixmp,0)=eycore
=3, phi=constant & ey(ixmp,0)=eycore
>3 or < 1 now unavailable, previously
dphi(ix,1)=dphi_iy1,isutcore ctrls ix=ixmp

Tom and the others have been pretty good about commenting variables that are visible from the parser. You should be able to add that to your notebook.

Bill

________________________________

**Comment by holm10** [comment]
Closed as resolved
