### ISSUE TITLE
a old toolbox for UEDGE

### ISSUE THREAD

**Issue by jguterl** [LLNL/UEDGE#39]
https://github.com/jguterl/UEDGEToolBox

**Comment by holm10** [comment]
Thanks @jguterl, I remember you mentioning having this toolbox, but I didn't know whether it was public yet or not! I will have a look at the toolbox and get back to you with questions and see if there are things that could be useful to implement :)

**Comment by holm10** [comment]
A separate repo for a central set of maintained tools has been created and launched at https://github.com/LLNL/UETOOLS/. If there are capabilities in the UEDGEToolBox that are not available in UETOOLS, a PR can be opened and merged.
