### ISSUE TITLE
Bug? from Real to Int

### ISSUE THREAD

**Issue by liruipeng** [LLNL/UEDGE#80]
**Describe the bug**
These two lines look suspicious (caught by compilers warnings)

https://github.com/LLNL/UEDGE/blob/a6245d233dce697dcfce7718e7f99418711b5c2f/bbb/turbulence.m#L169C1-L170C24

Do we really want to cast them into int?

**Comment by holm10** [comment]
Hi Rui Peng, this is probably an oversight and the variables should be cast as float. On a more general note, this particular routine appears to be deprecated to the point we're likely to remove it from the code altogether.

Many thanks for bringing this to our attention!
